import type { LanguageCode } from '@/lib/constants/languages';

export type RecordingPromptMode = 'script' | 'custom';

export const VOICE_SAMPLE_SCRIPTS: Partial<Record<LanguageCode, string>> = {
  en: `At the edge of the harbor, the last ferry had already left, but Mara stayed on the pier with a paper lantern in her hands. The wind smelled like rain and salt, and every wave tapped the wooden posts as if it were delivering a secret message. She laughed softly, tucked a loose strand of hair behind her ear, and said that missing the boat was not a disaster after all. It only meant the night had chosen a slower, more beautiful story for them to follow.`,
  zh: `在港口边缘，最后一班渡船已经离开了，可玛拉仍然站在码头上，手里提着一盏纸灯笼。风里带着雨水和海盐的气味，每一阵浪都轻轻敲着木桩，像是在送来一条秘密消息。她轻声笑了笑，把散落的发丝别到耳后，说错过那条船其实并不算灾难。那只是说明，这个夜晚为他们选了一段更缓慢、也更动人的故事。`,
  ja: `港のはずれでは、最後のフェリーがもう出たあとだったが、マーラは紙の灯りを手にして桟橋に残っていた。風は雨と潮の匂いを運び、波が木の杭をたたくたびに、まるで秘密の知らせを届けているようだった。彼女は小さく笑い、頬にかかった髪を耳にかけながら、船に乗り遅れたことはそれほど悪いことではないと言った。それはただ、この夜がもっとゆっくり進む物語を選んだということだった。`,
  ko: `항구 끝자락에서 마지막 페리는 이미 떠났지만, 마라는 종이 등불을 든 채 부두에 그대로 서 있었다. 바람에는 비와 바다 소금 냄새가 섞여 있었고, 파도는 나무 말뚝을 두드릴 때마다 마치 비밀스러운 소식을 전하는 것처럼 들렸다. 그녀는 작게 웃으며 흘러내린 머리카락을 귀 뒤로 넘기고, 배를 놓친 일이 꼭 재앙은 아니라고 말했다. 그 말은 결국 오늘 밤이 우리에게 조금 더 천천히 흘러가는 이야기를 골라 주었다는 뜻이었다.`,
  de: `Am Rand des Hafens war die letzte Faehre schon fort, doch Mara blieb mit einer Papierlaterne in der Hand auf dem Steg stehen. Der Wind roch nach Regen und Salz, und jede Welle klopfte gegen die Holzpfaehle, als wuerde sie eine geheime Nachricht bringen. Sie lachte leise, strich sich eine lose Haarstraehne hinters Ohr und sagte, dass das verpasste Boot kein Unglueck sei. Es bedeute nur, dass die Nacht fuer sie eine langsamere und schoenere Geschichte ausgesucht habe.`,
  fr: `Au bord du port, le dernier ferry etait deja parti, mais Mara restait sur le quai avec une lanterne de papier entre les mains. Le vent sentait la pluie et le sel, et chaque vague frappait les pilotis comme si elle apportait un message secret. Elle a souri doucement, a replace une meche derriere son oreille et a dit que rater le bateau n'etait pas vraiment une catastrophe. Cela voulait simplement dire que la nuit avait choisi pour eux une histoire plus lente et plus belle.`,
  ru: `На краю гавани последний паром уже ушел, но Мара все еще стояла на причале с бумажным фонарем в руках. Ветер пах дождем и солью, а каждая волна постукивала по деревянным сваям так, словно приносила тайное послание. Она тихо рассмеялась, убрала выбившуюся прядь волос за ухо и сказала, что опоздать на лодку вовсе не беда. Это значит лишь то, что ночь выбрала для них более медленную и красивую историю.`,
  pt: `Na beira do porto, a ultima balsa ja tinha partido, mas Mara continuava no pier com uma lanterna de papel nas maos. O vento cheirava a chuva e sal, e cada onda batia nos pilares de madeira como se trouxesse uma mensagem secreta. Ela sorriu de leve, colocou uma mecha solta atras da orelha e disse que perder o barco nao era exatamente um desastre. Aquilo so significava que a noite tinha escolhido para eles uma historia mais lenta e mais bonita.`,
  es: `En el borde del puerto, el ultimo ferry ya se habia ido, pero Mara seguia en el muelle con una linterna de papel entre las manos. El viento olia a lluvia y a sal, y cada ola golpeaba los postes de madera como si trajera un mensaje secreto. Ella sonrio en voz baja, se acomodo un mechon detras de la oreja y dijo que perder el barco no era realmente una tragedia. Solo significaba que la noche habia elegido para ellos una historia mas lenta y mas hermosa.`,
  it: `Sul bordo del porto, l'ultimo traghetto era gia partito, ma Mara era rimasta sul molo con una lanterna di carta tra le mani. Il vento sapeva di pioggia e di sale, e ogni onda bussava ai pali di legno come se portasse un messaggio segreto. Lei rise piano, si sistemo una ciocca dietro l'orecchio e disse che perdere la barca non era affatto una tragedia. Significava soltanto che la notte aveva scelto per loro una storia piu lenta e piu bella.`,
};

export function getVoiceSampleScript(language: LanguageCode): string {
  return VOICE_SAMPLE_SCRIPTS[language] || VOICE_SAMPLE_SCRIPTS.en || '';
}
